name: CI
on: [push, pull_request]

jobs:
  build-generic:
    name: Build Generic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16 LTS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: npm install -f

      - name: Run tests
        run: gulp generic

      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v2
        with:
          name: scholarly-pdf.js
          path: ./build/generic/
